### ISSUE TITLE
Finish brownFuncs.sh

### ISSUE THREAD

**Issue by deavmi** [deavmi/brownie#1]
Finish the `brownFuncs.sh` file.

**Comment by deavmi** [comment]
@Walkman100 What functions would you like to see implemented?

**Comment by Walkman100** [comment]
what

**Comment by deavmi** [comment]
@Walkman100 Make suggestions of functions you'd like

**Comment by deavmi** [comment]
@deavmi :)

**Comment by Walkman100** [comment]
What is this

**Comment by deavmi** [comment]
Nvm. Explain later. Its basically a way to add functions to `.bashrc` with pre-written functions.

**Comment by deavmi** [comment]
Switched to aliases. This can be closed. Plus we have finished most aliases just waiting for users to submit more. :)
