### ISSUE TITLE
Source files after install

### ISSUE THREAD

**Issue by deavmi** [deavmi/brownie#3]
Source `brownFuncs.sh` after install as to allow the changes to be applied immediately as the newly added functions in the `.bashrc` will only be applied next time bash starts up.

**Comment by deavmi** [comment]
@Walkman100 should I add this?

**Comment by deavmi** [comment]
Not doing this.

**Comment by Walkman100** [comment]
why not? sounds good. if not, then at least have a notice saying the aliases will only be loaded on next terminal startup.

**Comment by deavmi** [comment]
Actually I can;t do this. the installer runs in a separate bash process; sourcing will have no affect after the bash process ends when no more bash code in the installer is found.

I will tell the user that info though about the aliases being applied later.

**Comment by Walkman100** [comment]
@deavmi oh ok, cool

**Comment by deavmi** [comment]
Yep. :) will do
